# Generated by Django 2.1.7 on 2019-04-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_text',
        ),
    ]
